version: '3.7'
services:
  server:
    image: nginx
    init: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.template.conf:/etc/nginx/conf.d/default_template
    ports:
      - "8001:80"
    depends_on:
      - express
    links:
      - express
    environment:
      NGINX_PORT: 80
    env_file:
      - ../.env
    command: /bin/sh -c "envsubst '$$PORT' < /etc/nginx/conf.d/default_template> /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"


  express:
    tty: true
    stdin_open: true
    image: node:alpine
    init: true
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    command: ['bin/www']
